apiVersion: v1
kind: Service
metadata:
  name: molecule-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: boomi-aks
  labels:
    app: molecule
spec:
  selector:
    app: molecule
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
